sudo: False

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest heapdict numpy nomkl
  - source activate test

  - python setup.py install

script:
  - py.test --doctest-modules cachey

notifications:
  email: false
